### ISSUE TITLE
Fix the delete/backspace button functionality

### ISSUE THREAD

**Issue by ShivSt** [ShivSt/MyCalc#1]
The backspace key should delete each digit one by one on i/p and give the recalculated result on the o/p

**Comment by Being-Maverick** [comment]
Please assign this issue to me.

**Comment by darsh8114** [comment]
Can I Work on this ?

**Comment by ShivSt** [comment]
Good work here Darsh. But, there is some issue. It doesnot work beyond 3-4 backspace. So thats the improvement needed. Still great for start
